# ESPHome Dial Menu - M5Stack Dial
# Simplified configuration - LVGL UI is generated automatically!
#
substitutions:
  device_name: dial-menu
  friendly_name: Dial Menu

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG

# === Custom fonts with French characters ===
font:
  - file: "gfonts://Montserrat"
    id: montserrat_fr_14
    size: 14
    bpp: 4
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°àâäçèéêëîïôùûüÿœæÀÂÄÇÈÉÊËÎÏÔÙÛÜŸŒÆ"
  - file: "gfonts://Montserrat"
    id: montserrat_fr_18
    size: 18
    bpp: 4
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°àâäçèéêëîïôùûüÿœæÀÂÄÇÈÉÊËÎÏÔÙÛÜŸŒÆ"

external_components:
  - source:
      type: local
      path: components
    components: [dial_menu]

# === WiFi for time sync ===
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name}-fallback"

# === Time source ===
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Paris

# === Hardware Configuration ===

i2c:
  - id: internal_i2c
    sda: GPIO11
    scl: GPIO12

spi:
  id: spi_bus
  mosi_pin: GPIO5
  clk_pin: GPIO6

# === Display ===
display:
  - platform: ili9xxx
    id: round_display
    model: GC9A01A
    cs_pin: GPIO7
    dc_pin: GPIO4
    reset_pin: GPIO8
    invert_colors: true
    dimensions:
      width: 240
      height: 240
    auto_clear_enabled: false
    update_interval: never

# === Touch ===
touchscreen:
  - platform: ft63x6
    id: dial_touch
    interrupt_pin: GPIO14
    i2c_id: internal_i2c

# === Backlight ===
output:
  - platform: ledc
    pin: GPIO9
    id: backlight_output

light:
  - platform: monochromatic
    output: backlight_output
    name: "Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# === Encoder ===
sensor:
  - platform: rotary_encoder
    id: dial_encoder
    name: "Dial Encoder"
    pin_a: GPIO40
    pin_b: GPIO41
    resolution: 1
    on_clockwise:
      then:
        - lambda: |-
            id(menu_controller).on_encoder_rotate(1);
    on_anticlockwise:
      then:
        - lambda: |-
            id(menu_controller).on_encoder_rotate(-1);

binary_sensor:
  - platform: gpio
    id: dial_button
    name: "Dial Button"
    pin:
      number: GPIO42
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      # Short click - open selected app or toggle switch
      - timing:
          - ON for at most 400ms
          - OFF for at least 50ms
        then:
          - lambda: |-
              id(menu_controller).on_button_click();
      # Long press - go back to launcher
      - timing:
          - ON for at least 500ms
        then:
          - lambda: |-
              id(menu_controller).on_long_press();

# === Test Switches ===
switch:
  - platform: template
    id: light_living_room
    name: "Salon"
    optimistic: true
  - platform: template
    id: light_bedroom
    name: "Chambre"
    optimistic: true
  - platform: template
    id: light_kitchen
    name: "Cuisine"
    optimistic: true
  - platform: template
    id: light_bathroom
    name: "Salle de bain"
    optimistic: true

# === LVGL (minimal config - UI is created by dial_menu) ===
lvgl:
  displays:
    - round_display
  touchscreens:
    - dial_touch
  encoders:
    - sensor: dial_encoder
      enter_button: dial_button
  buffer_size: 25%
  
  # Use built-in montserrat_48 as default for idle screen
  default_font: montserrat_48

  # We need a page to avoid hello_world, and widgets to enable LVGL features
  # Hidden labels force compilation of needed font sizes
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        # Hidden widgets to enable LVGL btn/label support and compile fonts
        - button:
            id: _hidden_btn
            hidden: true
        - label:
            id: _hidden_label
            hidden: true
        - label:
            id: _font_14
            hidden: true
            text_font: montserrat_14
        - label:
            id: _font_18
            hidden: true
            text_font: montserrat_18
        - label:
            id: _font_28
            hidden: true
            text_font: montserrat_28
        # French font labels to force compilation
        - label:
            id: _font_fr_14
            hidden: true
            text_font: montserrat_fr_14
        - label:
            id: _font_fr_18
            hidden: true
            text_font: montserrat_fr_18

# === Dial Menu - That's it! ===
dial_menu:
  id: menu_controller
  display_id: round_display
  time_id: sntp_time
  idle_timeout: 30s
  language: fr  # Options: en, fr
  font_14: montserrat_fr_14  # Custom font with French accents
  font_18: montserrat_fr_18
  apps:
    - name: "Settings"
      icon_type: settings
      color: 0xFD5C4C
    - name: "WiFi"
      icon_type: wifi
      color: 0x577EFF
    - name: "Timer"
      icon_type: timer
      color: 0x03A964
    - name: "Brightness"
      icon_type: brightness
      color: 0xEB8429
    - name: "Temperature"
      icon_type: temperature
      color: 0x1AA198
    - name: "Music"
      icon_type: music
      color: 0x9C27B0
    - name: "Light"
      icon_type: light
      color: 0xFFB300
    - name: "Lumières"
      type: switch
      icon_type: light
      color: 0xFFB300
      switches:
        - switch_id: light_living_room
          name: "Salon"
          color: 0xFFB300
        - switch_id: light_bedroom
          name: "Chambre"
          color: 0x9C27B0
        - switch_id: light_kitchen
          name: "Cuisine"
          color: 0x03A964
        - switch_id: light_bathroom
          name: "Bathroom"
          color: 0x577EFF
