# ESPHome Dial Menu - Minimal Example
# Copy this to ESPHome Dashboard and it will work!
#
# All dependencies are imported from GitHub - nothing else needed.
#
substitutions:
  device_name: my-dial
  friendly_name: My Dial

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# === Import everything from GitHub ===
packages:
  m5dial: github://antorfr/esphome-dial/packages/m5stack_dial.yaml@main
  lvgl_config: github://antorfr/esphome-dial/packages/dial_menu_lvgl.yaml@main
  # french_fonts: github://antorfr/esphome-dial/packages/french_fonts.yaml@main  # Uncomment for French

external_components:
  - source: github://antorfr/esphome-dial@main
    components: [dial_menu]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: sntp_time

# === Encoder events (extend from package) ===
sensor:
  - platform: rotary_encoder
    id: !extend dial_encoder
    on_clockwise:
      - lambda: id(menu_controller).on_encoder_rotate(1);
    on_anticlockwise:
      - lambda: id(menu_controller).on_encoder_rotate(-1);

binary_sensor:
  - platform: gpio
    id: !extend dial_button
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 50ms
        then:
          - lambda: id(menu_controller).on_button_click();
      - timing:
          - ON for at least 500ms
        then:
          - lambda: id(menu_controller).on_long_press();

# === Your switches ===
switch:
  - platform: template
    id: my_light
    name: "Light"
    optimistic: true

# === Dial Menu ===
dial_menu:
  id: menu_controller
  display_id: round_display
  time_id: sntp_time
  apps:
    - name: "Settings"
      icon_type: settings
      color: 0xFD5C4C
    - name: "Light"
      type: switch
      icon_type: light
      switch_id: my_light
      color: 0xFFB300
